import { IVideoTemp } from "../interfaces/Movies";

export const skeletonData: IVideoTemp[] = [
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
  {
    id: 0,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
  },
];
